### ISSUE TITLE
Calipseo-shiny GitHub matters

### ISSUE THREAD

**Issue by lautarofao** [un-fao/calipseo-shiny#209]
This ticket is for tracking the Github activities for Calipseo-shiny.

**Comment by eblondel** [comment]
Thanks @lautarofao i've contacted @edmachado-fao by email. Token was set and operational for writing Github packages. Now waiting to have the writen package (docker published image) set visible to public at https://github.com/un-fao/calipseo-shiny/pkgs/container/calipseo-shiny (by default Github makes it private). We tried but @kviparthi doesn't have the privileges for this.

**Comment by eblondel** [comment]
@lautarofao @edmachado-fao a kind reminder on above request. We need to have the docker package visibility set to public to keep on working on Shinyproxy for deploying the app. Thanks in advance

cc NFI @yannlaurent @kviparthi

**Comment by eblondel** [comment]
@lautarofao @edmachado-fao kind reminder

cc @NFI @yannlaurent @kviparthi

**Comment by lautarofao** [comment]
Hi @eblondel, thanks for letting us know, please let me follow up with @edmachado-fao. 
I'll get you an update on this as soon as possible.

**Comment by eblondel** [comment]
Hi @lautarofao @edmachado-fao any news on that? Changing the package visibility to 'public' is one button click btw; and it's prequisite for us to work with shinyproxy. I remind you that this repository has already been turned to public, so we do need asap the equivalent as public docker image.

cc @kviparthi @yannlaurent

**Comment by lautarofao** [comment]
Hi @eblondel, Yes, we discussed this with Eduardo. 
We would need, at least, the appropriate project description in this repository's Readme to make the docket registry available to the public. Can you please fill in the project Readme?
Thanks for your understanding and collaboration.

**Comment by lautarofao** [comment]
Hi Eduardo, I wonder if we can publicize this URL: https://github.com/orgs/un-fao/packages. Will publicizing this URL allow us to have private and public packages? I tried to access the settings, but they seem available only to organization owners. Please advise.

Thanks
@edmachado-fao

**Comment by lautarofao** [comment]
Hi @eblondel, we have made the necessary changes to make the package visible to the public.
The previously published one inhered the visibility at the moment, which was private. 
Can you try publishing it again to see if that's being published as public?
cc: @edmachado-fao

**Comment by eblondel** [comment]
@lautarofao https://github.com/un-fao/calipseo-shiny/pkgs/container/calipseo-shiny is still marked as private, are you sure you changed the visibility of this repo packages? I don't think so, while instead we can see the packages list of the org https://github.com/orgs/un-fao/packages

**Comment by lautarofao** [comment]
@eblondel Can you try publishing it again please?

**Comment by eblondel** [comment]
I triggered it, but as long as the repo package is not set as Public, images will not be public. I already did this in other repositories and that's the way Github packages work.

**Comment by edmachado-fao** [comment]
Hi everyone,

The package access has been set to public.  Emmanuel , can you please  confirm on your side?

Regards,
Eduardo

________________________________

**Comment by eblondel** [comment]
Hi @edmachado-fao right now yes it is public, I confirm. Thanks

**Comment by lautarofao** [comment]
Thanks for confirming, @eblondel. Closing this issue now.
